openapi: "3.0.0"
info:
    version: 1.0.0
    title: Secret Management API
    description: Secure secret management for connectors

paths:
    /admin-api/v1/secret/secrets:
        $ref: "./parts/secrets-path.yaml"
    /admin-api/v1/secret/secrets/generate:
        $ref: "./parts/secrets-generate-path.yaml"
    /admin-api/v1/secret/secrets/{id}:
        $ref: "./parts/secrets-id-path.yaml"
    /admin-api/v1/secret/secrets/{id}/revoke:
        $ref: "./parts/secrets-id-revoke-path.yaml"

components:
    $ref: "./secret-schema.yaml#/components"
