// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SecrSecret struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// AES-256-GCM ciphertext (base64). Nonce prepended. Never store plaintext.
	EncryptedValue string `json:"encrypted_value"`
	// Encryption key version used — enables key rotation without re-encrypting all rows
	KeyVersion    int32       `json:"key_version"`
	ConnectorType string      `json:"connector_type"`
	Description   pgtype.Text `json:"description"`
	// active | revoked
	Status    string      `json:"status"`
	TenantID  pgtype.Text `json:"tenant_id"`
	CreatedBy pgtype.Text `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
