// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSecrets = `-- name: CountSecrets :one
SELECT COUNT(*) FROM secr_secrets
WHERE ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text   IS NULL OR status     = $2)
  AND ($3::text IS NULL OR connector_type = $3)
`

type CountSecretsParams struct {
	TenantID      pgtype.Text `json:"tenant_id"`
	Status        pgtype.Text `json:"status"`
	ConnectorType pgtype.Text `json:"connector_type"`
}

func (q *Queries) CountSecrets(ctx context.Context, arg CountSecretsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSecrets, arg.TenantID, arg.Status, arg.ConnectorType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secr_secrets (
    name,
    encrypted_value,
    key_version,
    connector_type,
    description,
    tenant_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at
`

type CreateSecretParams struct {
	Name           string      `json:"name"`
	EncryptedValue string      `json:"encrypted_value"`
	KeyVersion     int32       `json:"key_version"`
	ConnectorType  string      `json:"connector_type"`
	Description    pgtype.Text `json:"description"`
	TenantID       pgtype.Text `json:"tenant_id"`
	CreatedBy      pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (SecrSecret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.Name,
		arg.EncryptedValue,
		arg.KeyVersion,
		arg.ConnectorType,
		arg.Description,
		arg.TenantID,
		arg.CreatedBy,
	)
	var i SecrSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.KeyVersion,
		&i.ConnectorType,
		&i.Description,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secr_secrets WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecretByID = `-- name: GetSecretByID :one
SELECT id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at FROM secr_secrets WHERE id = $1
`

func (q *Queries) GetSecretByID(ctx context.Context, id uuid.UUID) (SecrSecret, error) {
	row := q.db.QueryRow(ctx, getSecretByID, id)
	var i SecrSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.KeyVersion,
		&i.ConnectorType,
		&i.Description,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByName = `-- name: GetSecretByName :one
SELECT id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at FROM secr_secrets
WHERE name = $1
  AND tenant_id IS NOT DISTINCT FROM $2::text
  AND status = 'active'
`

type GetSecretByNameParams struct {
	Name     string      `json:"name"`
	TenantID pgtype.Text `json:"tenant_id"`
}

// tenant_id is matched with IS NOT DISTINCT FROM, so a NULL argument means
// "the platform-scoped row" (tenant_id IS NULL) and NOT "any tenant's row".
// The previous (narg IS NULL OR tenant_id = narg) form collapsed to TRUE on a
// NULL argument and returned an arbitrary tenant's secret — a cross-tenant
// credential leak, since the query has no ORDER BY.
func (q *Queries) GetSecretByName(ctx context.Context, arg GetSecretByNameParams) (SecrSecret, error) {
	row := q.db.QueryRow(ctx, getSecretByName, arg.Name, arg.TenantID)
	var i SecrSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.KeyVersion,
		&i.ConnectorType,
		&i.Description,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at FROM secr_secrets
WHERE ($1::text IS NULL OR tenant_id = $1)
  AND ($2::text   IS NULL OR status     = $2)
  AND ($3::text IS NULL OR connector_type = $3)
ORDER BY created_at DESC
LIMIT  $5::int
OFFSET $4::int
`

type ListSecretsParams struct {
	TenantID      pgtype.Text `json:"tenant_id"`
	Status        pgtype.Text `json:"status"`
	ConnectorType pgtype.Text `json:"connector_type"`
	Offset        int32       `json:"offset"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]SecrSecret, error) {
	rows, err := q.db.Query(ctx, listSecrets,
		arg.TenantID,
		arg.Status,
		arg.ConnectorType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecrSecret{}
	for rows.Next() {
		var i SecrSecret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EncryptedValue,
			&i.KeyVersion,
			&i.ConnectorType,
			&i.Description,
			&i.Status,
			&i.TenantID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSecret = `-- name: RevokeSecret :one
UPDATE secr_secrets
SET status     = 'revoked',
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at
`

func (q *Queries) RevokeSecret(ctx context.Context, id uuid.UUID) (SecrSecret, error) {
	row := q.db.QueryRow(ctx, revokeSecret, id)
	var i SecrSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.KeyVersion,
		&i.ConnectorType,
		&i.Description,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secr_secrets
SET name            = $2,
    encrypted_value = $3,
    key_version     = $4,
    connector_type  = $5,
    description     = $6,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, name, encrypted_value, key_version, connector_type, description, status, tenant_id, created_by, created_at, updated_at
`

type UpdateSecretParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	EncryptedValue string      `json:"encrypted_value"`
	KeyVersion     int32       `json:"key_version"`
	ConnectorType  string      `json:"connector_type"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (SecrSecret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.Name,
		arg.EncryptedValue,
		arg.KeyVersion,
		arg.ConnectorType,
		arg.Description,
	)
	var i SecrSecret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.KeyVersion,
		&i.ConnectorType,
		&i.Description,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
