// Package secret provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package secret

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ListSecretsParams defines parameters for ListSecrets.
type ListSecretsParams struct {
	// Status Filter by status (active, revoked)
	Status *SecretStatus `form:"status,omitempty" json:"status,omitempty"`

	// ConnectorType Filter by connector type
	ConnectorType *string `form:"connector_type,omitempty" json:"connector_type,omitempty"`

	// TenantId Filter by tenant ID (SUPER_ADMIN only)
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
	Page     *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody = CreateSecretRequest

// GenerateSecretJSONRequestBody defines body for GenerateSecret for application/json ContentType.
type GenerateSecretJSONRequestBody = GenerateSecretRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin-api/v1/secret/secrets)
	ListSecrets(c *gin.Context, params ListSecretsParams)

	// (POST /admin-api/v1/secret/secrets)
	CreateSecret(c *gin.Context)

	// (POST /admin-api/v1/secret/secrets/generate)
	GenerateSecret(c *gin.Context)

	// (DELETE /admin-api/v1/secret/secrets/{id})
	DeleteSecret(c *gin.Context, id openapi_types.UUID)

	// (POST /admin-api/v1/secret/secrets/{id}/revoke)
	RevokeSecret(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListSecrets operation middleware
func (siw *ServerInterfaceWrapper) ListSecrets(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSecretsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "connector_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "connector_type", c.Request.URL.Query(), &params.ConnectorType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter connector_type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "tenant_id", c.Request.URL.Query(), &params.TenantId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tenant_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSecrets(c, params)
}

// CreateSecret operation middleware
func (siw *ServerInterfaceWrapper) CreateSecret(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSecret(c)
}

// GenerateSecret operation middleware
func (siw *ServerInterfaceWrapper) GenerateSecret(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateSecret(c)
}

// DeleteSecret operation middleware
func (siw *ServerInterfaceWrapper) DeleteSecret(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSecret(c, id)
}

// RevokeSecret operation middleware
func (siw *ServerInterfaceWrapper) RevokeSecret(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeSecret(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin-api/v1/secret/secrets", wrapper.ListSecrets)
	router.POST(options.BaseURL+"/admin-api/v1/secret/secrets", wrapper.CreateSecret)
	router.POST(options.BaseURL+"/admin-api/v1/secret/secrets/generate", wrapper.GenerateSecret)
	router.DELETE(options.BaseURL+"/admin-api/v1/secret/secrets/:id", wrapper.DeleteSecret)
	router.POST(options.BaseURL+"/admin-api/v1/secret/secrets/:id/revoke", wrapper.RevokeSecret)
}
