// Package secret provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package secret

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SecretStatus.
const (
	Active  SecretStatus = "active"
	Revoked SecretStatus = "revoked"
)

// CreateSecretRequest Payload for POST /admin-api/v1/secret/secrets. `value`
// is stored encrypted (AES-256-GCM); it is never echoed
// back by any endpoint.
type CreateSecretRequest struct {
	// ConnectorType Consumer hint (lre_api, smtp, openai…)
	ConnectorType string  `json:"connector_type"`
	Description   *string `json:"description"`

	// Name Unique name within the tenant
	Name string `json:"name"`

	// Value Plaintext; encrypted at rest
	Value string `json:"value"`
}

// Secret defines model for Secret.
type Secret struct {
	// ConnectorType Type of connector this secret belongs to (e.g. smtp, slack, stripe)
	ConnectorType string    `json:"connector_type"`
	CreatedAt     time.Time `json:"created_at"`
	CreatedBy     *string   `json:"created_by"`

	// Description Optional human-readable note about this secret
	Description *string            `json:"description"`
	Id          openapi_types.UUID `json:"id"`

	// Name Human-readable name for this secret, unique per tenant
	Name string `json:"name"`

	// Status Status of a secret
	Status    SecretStatus `json:"status"`
	TenantId  *string      `json:"tenant_id"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// SecretStatus Status of a secret
type SecretStatus string
